# -*- coding: utf-8 -*-
"""HTML_regex_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VE7h5Z0bIA_9eoHt3hN0ZmvPfhovYT8t
"""

import re

def convert_input_field(input_str):
    regex = r'\[\[invoerVeld_(\w+)_width_(\d+\.\d+)_height_(\d+\.\d+)\]\]'
    match = re.match(regex, input_str)

    if match:
        field_type, width, height = match.groups()
        output_html = f'''
            <div>
                <label for="{field_type}">Input ({field_type}):</label>
                <textarea id="{field_type}" name="{field_type}" rows="{height}" cols="{width}"></textarea>
            </div>
        '''
        return output_html
    else:
        return "Invalid input format"

input_str = "[[invoerVeld_klein_width_560.3_height_120.4]]"
output_html = convert_input_field(input_str)
print(output_html)