# -*- coding: utf-8 -*-
"""Molecular Biophysics Protein Folding

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UQPz-sTuVTUHBQgP1UJxEK7hos72sqNn
"""

import matplotlib.pyplot as plt
import numpy as np

def plot_deltaG(DeltaH, T0_Celsius):
    """
    Plots ΔG(T) vs Temperature (T) for protein folding/unfolding.

    Parameters:
    - DeltaH (float): Standard enthalpy change in J/mol.
    - T0_Celsius (float): Transition temperature in °C.
    """
    T0 = T0_Celsius + 273.15

    DeltaS = DeltaH / T0
    # Define temperature range: T0 ±30°C
    T_min_C = T0_Celsius - 30  # °C
    T_max_C = T0_Celsius + 30  # °C
    T_min = T_min_C + 273.15    # K
    T_max = T_max_C + 273.15    # K
    T = np.linspace(T_min, T_max, 400)  # Temperature array in K

    # Calculate ΔG(T) = ΔH - TΔS
    DeltaG = DeltaH - T * DeltaS

    # Folded state Gibbs free energy (Gf) assumed to be 0
    Gf = np.zeros_like(T)

    # Create the plot
    plt.figure(figsize=(10, 6))
    plt.plot(T, DeltaG, label=r'$\Delta G(T) = \Delta H - T\Delta S$', color='blue')
    plt.plot(T, Gf, '--', label='Folded State ($G_f(T)$)', color='gray')

    plt.ylim(-3000, 3000)
    plt.axhline(y=0, color='red', linestyle='--', linewidth=1)
    plt.axvline(x=T0, color='green', linestyle='--', linewidth=1, label=r'$T_0$')
    plt.grid(True, linewidth=1.0, linestyle='--', alpha=0.7)
    plt.annotate(
        r'$\Delta G = 0 \, \mathrm{J/mol}$',
        xy=(T_min, 0),
        xytext=(T_min + 20, -2500),
        arrowprops=dict(arrowstyle='->', color='red'),
        fontsize=10,
        color='red'
    )

    plt.annotate(
        f'X-intercept:\n$T_0$ = {T0_Celsius}°C',
        xy=(T0, 0),
        xytext=(T0 + 5, -2500),
        arrowprops=dict(arrowstyle='->', color='green'),
        fontsize=10,
        color='green'
    )

    plt.annotate(
        f'Slope: $-ΔS$ = -{DeltaS:.1f} J/(mol·K)',
        xy=((T_min + T_max) / 2, DeltaH - DeltaS*((T_min + T_max)/2)),
        xytext=((T_min + T_max) / 2, -2000),
        fontsize=10,
        color='blue'
    )

    plt.xlabel('Temperature (K)', fontsize=12)
    plt.ylabel(r'$\Delta G(T)$ (J/mol)', fontsize=12)
    plt.title(r'Gibbs Free Energy Change $\Delta G(T)$ vs. Temperature $T$', fontsize=14)
    plt.legend(fontsize=12)
    plt.tight_layout()
    plt.show()

DeltaH = 34000.0      # J/mol
T0_Celsius = 70.0     # °C
plot_deltaG(DeltaH, T0_Celsius)