# -*- coding: utf-8 -*-
"""Sorted Array.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15stl5C8gTB3kZWOArUFftmahV0Lt6SCn
"""

import numpy as np
Prelist = [30,30,30,30,40,40,40,40,10,10]
Prelist.sort()
print(Prelist)
Array = np.array(Prelist)

def SegmentData(Prelist):
  for i in range(len(Prelist)-4):
    n=i+1
    while Prelist[i] == Prelist[n]:
      np.delete(Prelist, n)
      n+= 1
SegmentData(Array)