# -*- coding: utf-8 -*-
"""ImmigratieDataPlotten.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sh0f6ZsYfiBj4zDy1YxY6kd4wzLlFlSD
"""

import matplotlib.pyplot as plt
import numpy as np

jaar_2021 = {
    "jan": 1346, "feb": 1364, "mrt": 1834, "apr": 1933,
    "mei": 1920, "jun": 2468, "jul": 3347, "aug": 3732,
    "sep": 5089, "okt": 5279, "nov": 4584, "dec": 3751
}

jaar_2022 = {
    "jan": 2720, "feb": 2518, "mrt": 4202, "apr": 3230,
    "mei": 3369, "jun": 3985, "jul": 4376, "aug": 4795,
    "sep": 5374, "okt": 4697, "nov": 4484, "dec": 4310
}

jaar_2023 = {
    "jan": 2991, "feb": 2823, "mrt": 3342, "apr": 3269,
    "mei": 3591, "jun": 4020, "jul": 4530, "aug": 4228,
    "sep": 4665, "okt": 6004
}

def gemiddelde_per_jaar(jaar):
    return sum(jaar) / len(jaar)

def concatenate_jaren(*jaren):
    concat_jaar = []
    concat_month_names = []
    for jaar in jaren:
        listed_month_names = list(jaar)
        listed_month_values = list(jaar.values())
        for index, element in enumerate(listed_month_values):
            concat_jaar.append(element)
            concat_month_names.append(listed_month_names[index])
    return concat_jaar, concat_month_names

def plot_continuous_trendlijn(values, maand_naam):
    maanden = maand_naam
    waardes = values

    numerieke_maanden = np.arange(1, len(maanden) + 1)

    gemiddelde = gemiddelde_per_jaar(values)
    trendlijn = np.polyfit(numerieke_maanden, waardes, 9)
    trendlijn_y = np.polyval(trendlijn, numerieke_maanden)

    plt.scatter(numerieke_maanden, waardes, label='2021-2023 - Data')
    plt.plot(numerieke_maanden, trendlijn_y, label='2021-2023 - Trendlijn', linestyle='--')
    plt.axhline(y=gemiddelde, color='r', linestyle='--', label='2021-2023 - Gemiddelde')
    plt.ylim(0, max(waardes) + 500)
    plt.xticks(numerieke_maanden[::3], maanden[::3])

concat_jaar, concat_month_names = concatenate_jaren(jaar_2021, jaar_2022, jaar_2023)
plot_continuous_trendlijn(concat_jaar, concat_month_names)

plt.xlabel('Maanden')
plt.ylabel('Aantal asielzoekers')
plt.title('Asielinstroom over de jaren')
plt.legend()
plt.show()