# -*- coding: utf-8 -*-
"""Read Sqlite.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hkXPgiWfoEe1-U7GRevmhXWXgRdJzflT
"""

import sqlite3
from google.colab import files

def upload_file():
    uploaded = files.upload()
    for filename in uploaded.keys():
        print('Uploaded file:', filename)
        return filename

def print_sqlite_head(db_file):
    conn = sqlite3.connect(db_file)
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM sqlite_master WHERE type='table';")
    tables = cursor.fetchall()
    for table in tables:
        table_name = table[1]
        print("Table:", table_name)
        cursor.execute(f"SELECT * FROM {table_name} LIMIT 5;")
        rows = cursor.fetchall()
        for row in rows:
            print(row)
    conn.close()

# Upload file
file_name = upload_file()

# Print head of SQLite database
print_sqlite_head(file_name)

def print_csv_head(db_file, table_name):
    conn = sqlite3.connect(db_file)
    cursor = conn.cursor()
    cursor.execute(f"SELECT * FROM {table_name} LIMIT 5;")
    rows = cursor.fetchall()
    for row in rows:
        csv_values = []
        for value in row:
            if isinstance(value, str) and "," in value:
                csv_values.append(value)
        if csv_values:
            print(csv_values)
    conn.close()

# Call the function to print CSV values in the "cards" table
print("CSV values in the 'cards' table:")
print_csv_head(file_name, "cards")