# -*- coding: utf-8 -*-
"""check ports.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11L9OWcJVT4IPc6YWUk3LDid17GzdseEF
"""

import socket

def check_port(ip, port):
    try:
        # Create a socket object
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        # Set timeout for the socket (5 seconds)
        sock.settimeout(5)
        # Try to connect to the server at the IP and port
        result = sock.connect_ex((ip, port))

        if result == 0:
            print(f"Port {port} on xx.xx.xx.xx is OPEN")
        else:
            print(f"Port {port} on xx.xx.xx.xx is CLOSED or BLOCKED")

        # Close the socket after the attempt
        sock.close()

    except socket.error as e:
        print(f"Error checking port {port} on {ip}: {e}")

# Replace with the IP address and port number you want to check
ip_address = "95.99.68.34"  # Example IP address
port_number = 5060  # Example port

check_port(ip_address, port_number)