# -*- coding: utf-8 -*-
"""Count Lines in Txt File.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QgZGF2JsBrDunpHuHPwRdPR9A_djqMWC
"""

# Colab script to count the lines in a .txt file
from google.colab import files

uploaded = files.upload()

file_name = list(uploaded.keys())[0]

def count_lines(file_path):
    with open(file_path, 'r') as file:
        lines = file.readlines()
        return len(lines)

line_count = count_lines(file_name)
print(f"The file '{file_name}' has {line_count} lines.")